appinst: test if the url ends with a file

diff --git a/src/appinst b/src/appinst
--- a/src/appinst
+++ b/src/appinst
@@ -32,8 +32,15 @@ if [[ "$EUID" == 0 ]]; then
 fi
 
 if [[ $url != "http"* ]]; then
-    echo "usage : appinst \"https://url/to/program\""
-    echo "usage : appinst -f \"https://url/to/program\""
+    echo "usage : appinst \"https://url/to/a_file\""
+    echo "usage : appinst -f \"https://url/to/a_file\""
+    echo "abort..."
+    exit 1
+fi
+
+if [[ $url == *"/" ]]; then
+    echo "*** url must point to a file such as :"
+    echo "\"https://url/to/a_file\""
     echo "abort..."
     exit 1
 fi
@@ -64,7 +71,8 @@ echo "type : $filetype"
 
 if [[ $force != 1 ]] \
 && [[ $filetype != "ELF"* ]] \
-&& [[ $filetype != "Bourne-Again shell script"* ]]; then
+&& [[ $filetype != "Bourne-Again shell script"* ]] \
+&& [[ $filetype != "Perl script"* ]]; then
     echo "*** file is not an ELF file or a bash script"
     echo "abort..."
     exit 1
