add error message

diff --git a/src/wallset b/src/wallset
--- a/src/wallset
+++ b/src/wallset
@@ -15,18 +15,20 @@ wallpaper_set()
     fi
     
     filepath="$wallpapers/$1"
-    test -f "$filepath" || usage_exit
+    test -f "$filepath" || error_exit "invalid file : $filepath"
     
     cp "$filepath" "$current"
     hsetroot -cover "$current"
 }
 
-usage_exit()
+error_exit()
 {
+    test "$1" == "" || echo "$1"; echo "abort..."; exit 1
     echo "*** usage :"
     echo "wallset"
     echo "wallset \"my_file.jpg\""
     echo "wallset -save \"my_file.jpg\""
+    echo "abort..."
     exit 1
 }
 
@@ -39,7 +41,7 @@ while (($#)); do
             test $# -gt 0 && shift; newname="$1"
         ;;
         *)
-            test "$filepath" == "" || usage_exit
+            test "$filepath" == "" || error_exit
             filepath="$1"
         ;;
     esac
@@ -47,7 +49,7 @@ while (($#)); do
 done
 
 if [[ $save == 1 ]]; then
-    test "$newname" != "" || usage_exit
+    test "$newname" != "" || error_exit
     echo "save : \"$newname\""
     cp "$HOME/.wallpaper" "$wallpapers/$newname"
     exit 0
